services:
  sqli-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: sqli-app
    volumes:
      - ./:/var/www/sqli
    depends_on:
    - mysql
    networks:
      - sqli

  nginx:
    image: nginx:alpine
    container_name: sqli-nginx
    ports:
      - "8005:80"
      - "443:443"
    volumes:
      - ./:/var/www/sqli
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certificates:/etc/nginx/certs:ro
    networks:
      - sqli

  mysql:
    image: mysql:latest
    container_name: sqli-mysql
    environment:
      MYSQL_DATABASE: sqli
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - dbdata:/var/lib/mysql
      - ./sqli_dump.sql:/docker-entrypoint-initdb.d/sqli_dump.sql:ro
    ports:
      - "3307:3306"
    networks:
      - sqli

  vite:
    image: node:20
    container_name: sqli-vite
    working_dir: /frontend
    volumes:
      - ./resources:/frontend/resources
      - ./public:/frontend/public
      - ./vite.config.js:/frontend/vite.config.js
      - ./package.json:/frontend/package.json
      - ./package-lock.json:/frontend/package-lock.json
      - ./.env:/frontend/.env:ro
      - ./nginx/certificates:/etc/nginx/certs:ro
    ports:
      - "5173:5173"
    command: sh -c "npm i && npm run dev"
    networks:
      - sqli


volumes:
  dbdata:

networks:
  sqli: